spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm-news?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化大小 ，最大，最小
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunMillis: 60000
      # 配置一个连接在池中的最小生存时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnRuturn: false
      # 打开 PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPrepareStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall' 用于防火墙
      filters: stat,wall,log4j
      # 通过 connectProperties 属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
      # 合并多个 DruidDataSource的监控数据
      # useGlobalDataSourceStat=true

  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
server:
  tomcat:
    uri-encoding: utf-8
  port: 8080
